"""Pi-specific native verification/finality profile for Koschei Lang v1.

Pi remains outside Lang core. The profile requires a sealed Pi ABI, exact-artifact
runtime admission, reproducibility-gated admission, current/live builder trust state and
raw Pi response verification before finality may enter the sanctioned chain.
"""
from __future__ import annotations
from typing import Callable
from .effect_execution_proof_envelope_v1 import EffectExecutionProofEnvelopeV1
from .effect_execution_receipt_v1 import EffectExecutionReceiptV1
from .external_finality_attestation_v1 import ExternalProviderFinalityVerdictV1
from .provider_adapter_abi_v1 import ProviderAdapterAbiV1
from .provider_finality_bridge_v1 import issue_provider_finality_verdict_from_native_receipt_v1
from .provider_native_verifier_v1 import ProviderNativeVerificationReceiptV1,ProviderNativeVerificationResultV1,verify_provider_native_response_v1
from .trust_anchor_admission_v1 import TrustAnchorGenerationStateV1
from .verifier_build_provenance_v1 import VerifierBuildProvenanceV1,VerifierRuntimeAdmissionV1
from .verifier_reproducible_admission_v1 import VerifierReproducibleRuntimeAdmissionV1
from .verifier_reproducible_build_v1 import VerifierReproducibleBuildReceiptV1
_PROVIDER_ID="pi"
class PiFinalityProfileV1Error(ValueError): pass
def _require_pi_abi(adapter_abi:ProviderAdapterAbiV1)->None:
    adapter_abi.assert_sealed()
    if adapter_abi.provider_id!=_PROVIDER_ID: raise PiFinalityProfileV1Error("Pi finality requires provider_id=pi")
def verify_pi_native_payment_response_v1(*,adapter_abi:ProviderAdapterAbiV1,runtime_admission:VerifierRuntimeAdmissionV1,reproducible_admission:VerifierReproducibleRuntimeAdmissionV1,reproducibility_receipt:VerifierReproducibleBuildReceiptV1,reproducibility_key:bytes,builder_a_generation_state:TrustAnchorGenerationStateV1,builder_b_generation_state:TrustAnchorGenerationStateV1,provenance:VerifierBuildProvenanceV1,verifier_artifact_bytes:bytes,build_provenance_key:bytes,runtime_admission_key:bytes,reproducible_admission_key:bytes,effect_envelope:EffectExecutionProofEnvelopeV1,effect_receipt:EffectExecutionReceiptV1,effect_result_txid_bytes:bytes,raw_pi_response_bytes:bytes,current_epoch:int,verifier:Callable[[bytes],ProviderNativeVerificationResultV1],provider_native_verifier_key:bytes,required_distinct_trust_roots:bool=False)->ProviderNativeVerificationReceiptV1:
    _require_pi_abi(adapter_abi)
    try:
        return verify_provider_native_response_v1(provider_id=_PROVIDER_ID,adapter_abi=adapter_abi,runtime_admission=runtime_admission,reproducible_admission=reproducible_admission,reproducibility_receipt=reproducibility_receipt,reproducibility_key=reproducibility_key,builder_a_generation_state=builder_a_generation_state,builder_b_generation_state=builder_b_generation_state,provenance=provenance,verifier_artifact_bytes=verifier_artifact_bytes,build_provenance_key=build_provenance_key,runtime_admission_key=runtime_admission_key,reproducible_admission_key=reproducible_admission_key,effect_envelope=effect_envelope,effect_receipt=effect_receipt,effect_result_bytes=effect_result_txid_bytes,raw_response_bytes=raw_pi_response_bytes,current_epoch=current_epoch,verifier=verifier,provider_native_verifier_key=provider_native_verifier_key,required_distinct_trust_roots=required_distinct_trust_roots)
    except ValueError as error: raise PiFinalityProfileV1Error(str(error)) from error
def issue_pi_finality_verdict_v1(*,native_receipt:ProviderNativeVerificationReceiptV1,adapter_abi:ProviderAdapterAbiV1,runtime_admission:VerifierRuntimeAdmissionV1,reproducible_admission:VerifierReproducibleRuntimeAdmissionV1,reproducibility_receipt:VerifierReproducibleBuildReceiptV1,reproducibility_key:bytes,builder_a_generation_state:TrustAnchorGenerationStateV1,builder_b_generation_state:TrustAnchorGenerationStateV1,provenance:VerifierBuildProvenanceV1,verifier_artifact_bytes:bytes,build_provenance_key:bytes,runtime_admission_key:bytes,reproducible_admission_key:bytes,effect_envelope:EffectExecutionProofEnvelopeV1,effect_receipt:EffectExecutionReceiptV1,effect_result_txid_bytes:bytes,raw_pi_response_bytes:bytes,current_epoch:int,provider_native_verifier_key:bytes,provider_verifier_key:bytes,required_distinct_trust_roots:bool=False)->ExternalProviderFinalityVerdictV1:
    _require_pi_abi(adapter_abi)
    if native_receipt.provider_id!=_PROVIDER_ID: raise PiFinalityProfileV1Error("Pi finality requires provider_id=pi")
    try:
        return issue_provider_finality_verdict_from_native_receipt_v1(native_receipt=native_receipt,adapter_abi=adapter_abi,runtime_admission=runtime_admission,reproducible_admission=reproducible_admission,reproducibility_receipt=reproducibility_receipt,reproducibility_key=reproducibility_key,builder_a_generation_state=builder_a_generation_state,builder_b_generation_state=builder_b_generation_state,provenance=provenance,verifier_artifact_bytes=verifier_artifact_bytes,build_provenance_key=build_provenance_key,runtime_admission_key=runtime_admission_key,reproducible_admission_key=reproducible_admission_key,effect_envelope=effect_envelope,effect_receipt=effect_receipt,effect_result_bytes=effect_result_txid_bytes,raw_response_bytes=raw_pi_response_bytes,current_epoch=current_epoch,provider_native_verifier_key=provider_native_verifier_key,provider_verifier_key=provider_verifier_key,required_distinct_trust_roots=required_distinct_trust_roots)
    except ValueError as error: raise PiFinalityProfileV1Error(str(error)) from error
