"""Bridge authenticated provider-native verification into finality verdicts v1."""
from __future__ import annotations
from .effect_execution_proof_envelope_v1 import EffectExecutionProofEnvelopeV1
from .effect_execution_receipt_v1 import EffectExecutionReceiptV1
from .external_finality_attestation_v1 import ExternalProviderFinalityVerdictV1,issue_external_provider_finality_verdict_v1
from .provider_adapter_abi_v1 import ProviderAdapterAbiV1
from .provider_native_verifier_v1 import ProviderNativeVerificationReceiptV1
from .trust_anchor_admission_v1 import TrustAnchorGenerationStateV1
from .verifier_build_provenance_v1 import VerifierBuildProvenanceV1,VerifierRuntimeAdmissionV1
from .verifier_reproducible_admission_v1 import VerifierReproducibleRuntimeAdmissionV1
from .verifier_reproducible_build_v1 import VerifierReproducibleBuildReceiptV1
class ProviderFinalityBridgeV1Error(ValueError): pass
def issue_provider_finality_verdict_from_native_receipt_v1(*,native_receipt:ProviderNativeVerificationReceiptV1,adapter_abi:ProviderAdapterAbiV1,runtime_admission:VerifierRuntimeAdmissionV1,reproducible_admission:VerifierReproducibleRuntimeAdmissionV1,reproducibility_receipt:VerifierReproducibleBuildReceiptV1,reproducibility_key:bytes,builder_a_generation_state:TrustAnchorGenerationStateV1,builder_b_generation_state:TrustAnchorGenerationStateV1,provenance:VerifierBuildProvenanceV1,verifier_artifact_bytes:bytes,build_provenance_key:bytes,runtime_admission_key:bytes,reproducible_admission_key:bytes,effect_envelope:EffectExecutionProofEnvelopeV1,effect_receipt:EffectExecutionReceiptV1,effect_result_bytes:bytes,raw_response_bytes:bytes,provider_native_verifier_key:bytes,provider_verifier_key:bytes)->ExternalProviderFinalityVerdictV1:
    adapter_abi.assert_sealed()
    native_receipt.assert_authenticated(provider_native_verifier_key=provider_native_verifier_key,adapter_abi=adapter_abi,runtime_admission=runtime_admission,reproducible_admission=reproducible_admission,reproducibility_receipt=reproducibility_receipt,reproducibility_key=reproducibility_key,builder_a_generation_state=builder_a_generation_state,builder_b_generation_state=builder_b_generation_state,provenance=provenance,verifier_artifact_bytes=verifier_artifact_bytes,build_provenance_key=build_provenance_key,runtime_admission_key=runtime_admission_key,reproducible_admission_key=reproducible_admission_key,effect_envelope=effect_envelope,effect_receipt=effect_receipt,effect_result_bytes=effect_result_bytes,raw_response_bytes=raw_response_bytes)
    verdict=issue_external_provider_finality_verdict_v1(provider_id=native_receipt.provider_id,effect_envelope=effect_envelope,external_reference_digest=native_receipt.verified_reference_digest,provider_proof_digest=native_receipt.provider_proof_digest,observed_epoch=native_receipt.observed_epoch,state=native_receipt.state,provider_verifier_key=provider_verifier_key)
    if verdict.external_reference_digest!=native_receipt.verified_reference_digest: raise ProviderFinalityBridgeV1Error("finality verdict reference differs from native receipt")
    if verdict.provider_proof_digest!=native_receipt.provider_proof_digest: raise ProviderFinalityBridgeV1Error("finality verdict proof differs from native receipt")
    if verdict.state!=native_receipt.state: raise ProviderFinalityBridgeV1Error("finality verdict state differs from native receipt")
    return verdict
