"""Koschei Universe Mobile View v1.

Touch-first read-only renderer for authority-free remote observer envelopes.
Authentication is carried only by the gateway's HttpOnly session cookie; browser
JavaScript never receives long-lived observer or signing credentials.
"""
from __future__ import annotations

MOBILE_HTML_V1 = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>Koschei Universe Mobile</title><style>
html,body{margin:0;height:100%;background:#02050d;color:#eaf2ff;font-family:ui-monospace,monospace;overflow:hidden}#c{width:100%;height:100%;display:block;touch-action:none}.top{position:fixed;left:10px;right:10px;top:10px;background:#07101ddd;border:1px solid #234767;border-radius:14px;padding:10px 12px;backdrop-filter:blur(8px);z-index:4}.top b{letter-spacing:.14em}.meta{font-size:11px;opacity:.8;margin-top:4px}.sheet{position:fixed;left:10px;right:10px;bottom:10px;max-height:34vh;overflow:auto;background:#07101eee;border:1px solid #234767;border-radius:14px;padding:12px;z-index:5}.hidden{display:none}.ok{color:#70ffb1}.warn{color:#ffd66d}.bad{color:#ff6f86}.tiny{font-size:11px;opacity:.82}.tag{display:inline-block;margin:6px 5px 0 0;padding:3px 7px;border:1px solid #31597b;border-radius:999px;font-size:10px;opacity:.85}</style></head><body>
<canvas id="c"></canvas><div class="top"><b>KOSCHEI UNIVERSE</b><div id="meta" class="meta">loading observer state…</div></div><div id="sheet" class="sheet hidden"></div>
<script>
const c=document.getElementById('c'),x=c.getContext('2d'),meta=document.getElementById('meta'),sheet=document.getElementById('sheet');let U=null,pts=[],scale=1,ox=0,oy=0,last=null,down=null,t0=performance.now();
function fit(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);layout()}addEventListener('resize',fit);fit();
function status(n){let ks=new Set((n.events||[]).map(e=>e.kind));if(n.quarantined||ks.has('fork')||ks.has('rollback')||ks.has('quarantine'))return'bad';if(ks.has('admission-denied')||ks.has('budget-block')||ks.has('authority-death'))return'warn';return'ok'}
function layout(){if(!U)return;let cx=innerWidth/2,cy=innerHeight*.54,unit=Math.min(innerWidth,innerHeight)/1500;pts=(U.nodes||[]).map(n=>{let sp=n.spatial||{},a=(sp.angleMicrorad||0)/1e6,r=(sp.radiusUnits||0)*unit,s=Math.max(14,(sp.sizeUnits||34)*unit);return{n,x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r,r:s}})}
function T(p){return{x:(p.x+ox-innerWidth/2)*scale+innerWidth/2,y:(p.y+oy-innerHeight/2)*scale+innerHeight/2,r:p.r*scale}}
function stars(){for(let i=0;i<120;i++){let px=(i*89+17)%innerWidth,py=(i*47+31)%innerHeight;x.fillStyle=i%9===0?'#9dc7ff30':'#ffffff18';x.fillRect(px,py,i%13===0?1.5:1,i%13===0?1.5:1)}}
function palette(n){let s=status(n);if(s==='bad')return'#ff5d78';if(s==='warn')return'#ffd05d';return({project:'#a878ff',service:'#5de6ff',storage:'#76d69b',guardian:'#8ba7ff',package:'#ff9c67',module:'#6fc7ff',test:'#d7a7ff',utility:'#b7c4d8'})[n.kind]||'#5de6ff'}
function planet(q,n,now){let col=palette(n);x.save();x.translate(q.x,q.y);x.shadowColor=col;x.shadowBlur=n.kind==='project'?30:16;x.strokeStyle=col;x.fillStyle=col+'33';x.lineWidth=n.kind==='project'?2.2:1.2;
 if(n.kind==='service'){x.rotate(now/3200);x.beginPath();for(let i=0;i<6;i++){let a=i*Math.PI/3,rr=i%2?q.r*.78:q.r;x.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}x.closePath();x.fill();x.stroke();x.beginPath();x.arc(0,0,q.r*.42,0,Math.PI*2);x.stroke()}
 else if(n.kind==='storage'){x.beginPath();x.arc(0,0,q.r*.86,0,Math.PI*2);x.fill();x.stroke();x.rotate(-.32);x.beginPath();x.ellipse(0,0,q.r*1.28,q.r*.38,0,0,Math.PI*2);x.stroke();x.beginPath();x.ellipse(0,0,q.r*1.05,q.r*.28,0,0,Math.PI*2);x.stroke()}
 else if(n.kind==='guardian'){x.beginPath();x.arc(0,0,q.r*.78,0,Math.PI*2);x.fill();x.stroke();for(let i=0;i<3;i++){x.beginPath();x.arc(0,0,q.r*(1.02+i*.18),now/1800+i,now/1800+i+Math.PI*.95);x.stroke()}}
 else if(n.kind==='package'||n.kind==='module'){x.beginPath();x.arc(0,0,q.r,0,Math.PI*2);x.fill();x.stroke();x.beginPath();x.arc(q.r*.28,-q.r*.22,q.r*.14,0,Math.PI*2);x.stroke();x.beginPath();x.arc(-q.r*.3,q.r*.18,q.r*.1,0,Math.PI*2);x.stroke()}
 else if(n.kind==='test'){x.setLineDash([3,3]);x.beginPath();x.arc(0,0,q.r,0,Math.PI*2);x.fill();x.stroke();x.setLineDash([]);x.beginPath();x.moveTo(-q.r*.45,0);x.lineTo(q.r*.45,0);x.moveTo(0,-q.r*.45);x.lineTo(0,q.r*.45);x.stroke()}
 else {x.beginPath();x.arc(0,0,q.r,0,Math.PI*2);x.fill();x.stroke();if(n.kind==='project'){x.beginPath();x.arc(0,0,q.r*.58,0,Math.PI*2);x.stroke();x.beginPath();x.arc(0,0,q.r*1.32,now/2400,now/2400+Math.PI*1.15);x.stroke()}}
 if(status(n)==='bad'){x.shadowBlur=0;x.strokeStyle='#ff2f50';for(let i=0;i<3;i++){x.beginPath();x.arc(0,0,q.r*(1.2+i*.18),now/420+i,now/420+i+.8);x.stroke()}}
 x.restore();return col}
function portal(A,B,e,now){let p=e.portal||{},style=p.style||'gravity-link',phase=(p.phaseMilli||0)/1000,pulse=Math.max(.65,(p.pulseMilli||1000)/1000),w=Math.max(.7,(p.widthMilli||1000)/1000)*scale;let t=(now/1000/pulse+phase)%1,dx=B.x-A.x,dy=B.y-A.y,mx=A.x+dx*t,my=A.y+dy*t;x.save();x.lineWidth=w;x.shadowBlur=0;
 if(style==='energy-conduit'){x.strokeStyle='#5de6ffaa';x.shadowColor='#5de6ff';x.shadowBlur=8;x.setLineDash([])}
 else if(style==='dashed-gate'){x.strokeStyle='#7ea2d488';x.setLineDash([5,6])}
 else if(style==='sensor-beam'){x.strokeStyle='#78ffd777';x.setLineDash([1,5]);x.lineWidth=Math.max(.6,w*.7)}
 else if(style==='anchor-bridge'){x.strokeStyle='#7fd39caa';x.setLineDash([]);x.lineWidth=w*1.15}
 else if(style==='simulation-rift'){x.strokeStyle='#d7a7ff99';x.setLineDash([2,4])}
 else if(style==='shield-arc'){x.strokeStyle='#8ba7ffbb';x.setLineDash([8,4]);x.lineWidth=w*1.1}
 else {x.strokeStyle='#6f82aa66';x.setLineDash([])}
 x.beginPath();x.moveTo(A.x,A.y);if(style==='shield-arc'){let nx=-dy*.08,ny=dx*.08;x.quadraticCurveTo((A.x+B.x)/2+nx,(A.y+B.y)/2+ny,B.x,B.y)}else{x.lineTo(B.x,B.y)}x.stroke();x.setLineDash([]);
 if(style!=='gravity-link'){let count=style==='energy-conduit'?7:1;for(let i=0;i<count;i++){let tt=(t-i*.035+1)%1,px=A.x+dx*tt,py=A.y+dy*tt,alpha=Math.max(.08,1-i/(count+1));x.globalAlpha=alpha;x.fillStyle=style==='energy-conduit'?(i%2?'#fff59d':'#5de6ff'):x.strokeStyle;x.shadowColor=x.fillStyle;x.shadowBlur=style==='energy-conduit'?14:8;x.beginPath();x.arc(px,py,Math.max(1.4,w*(style==='energy-conduit'?1.7-i*.12:1.4)),0,Math.PI*2);x.fill()}x.globalAlpha=1;if(style==='energy-conduit'){let ang=Math.atan2(dy,dx),bolt=10*scale;x.strokeStyle='#fff59dcc';x.lineWidth=Math.max(1,w*.55);x.shadowColor='#fff59d';x.shadowBlur=10;x.beginPath();x.moveTo(mx-Math.cos(ang)*bolt,my-Math.sin(ang)*bolt);x.lineTo(mx-Math.cos(ang)*bolt*.25-Math.sin(ang)*bolt*.35,my-Math.sin(ang)*bolt*.25+Math.cos(ang)*bolt*.35);x.lineTo(mx+Math.cos(ang)*bolt*.35,my+Math.sin(ang)*bolt*.35);x.lineTo(mx+Math.cos(ang)*bolt,my+Math.sin(ang)*bolt);x.stroke()}}
 x.restore()}
function draw(){requestAnimationFrame(draw);let now=performance.now()-t0;x.clearRect(0,0,innerWidth,innerHeight);stars();if(!U)return;let by=Object.fromEntries(pts.map(p=>[p.n.id,p]));for(let e of (U.edges||[])){let a=by[e.source],b=by[e.destination];if(!a||!b)continue;portal(T(a),T(b),e,now)}for(let p of pts){let q=T(p),col=planet(q,p.n,now);x.shadowBlur=0;x.fillStyle='#edf6ff';x.font=Math.max(9,10.5*scale)+'px ui-monospace';x.textAlign='center';let label=(p.n.id||'').replace(/^project:|^module:/,'');x.fillText(label,q.x,q.y+q.r+14);if(status(p.n)!=='ok'){x.fillStyle=col;x.fillText(status(p.n).toUpperCase(),q.x,q.y-q.r-8)}}}
function pick(px,py){return pts.find(p=>{let q=T(p);return Math.hypot(px-q.x,py-q.y)<=q.r+16})}
function show(n){let ev=(n.events||[]).map(e=>`<div class="tiny">${e.kind} · epoch ${e.epoch}</div>`).join('')||'<div class="tiny">no live events</div>';let sp=n.spatial||{};sheet.innerHTML=`<b>${n.id}</b><div class="${status(n)}">${n.kind} · ${status(n)}</div><div class="tag">ring ${sp.ring??'?'}</div><div class="tag">canonical spatial</div><div class="tag">authority-free observer</div>${ev}`;sheet.classList.remove('hidden')}
c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);last={id:e.pointerId,x:e.clientX,y:e.clientY};down={x:e.clientX,y:e.clientY}});c.addEventListener('pointermove',e=>{if(!last||last.id!==e.pointerId)return;ox+=(e.clientX-last.x)/scale;oy+=(e.clientY-last.y)/scale;last={id:e.pointerId,x:e.clientX,y:e.clientY}});c.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<8){let p=pick(e.clientX,e.clientY);if(p)show(p.n)}last=null;down=null});c.addEventListener('wheel',e=>{e.preventDefault();scale=Math.min(3,Math.max(.55,scale*(e.deltaY>0?.9:1.1)))},{passive:false});
async function load(){try{let r=await fetch('/api/observer',{cache:'no-store',credentials:'same-origin'});if(r.status===401){location.replace('/login');return}if(!r.ok)throw Error(r.status);let env=await r.json();let next=env.payload||env.universe||env;let changed=!U||U.projection!==next.projection||U.state!==next.state||U.layout!==next.layout||U.portals!==next.portals;U=next;meta.innerHTML=`epoch <span class="ok">${U.epoch??'?'}</span> · nodes ${(U.nodes||[]).length} · portals ${(U.portals||'').slice(0,8)} · read-only`;if(changed)layout()}catch(e){meta.innerHTML='<span class="bad">observer state unavailable</span>'}}
load();setInterval(load,2000);draw();
</script></body></html>'''
