"""Koschei Universe Mobile View v1.

Touch-first read-only renderer for authority-free remote observer envelopes.
Authentication is carried only by the gateway's HttpOnly session cookie; browser
JavaScript never receives long-lived observer or signing credentials.
"""
from __future__ import annotations

MOBILE_HTML_V1 = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>Koschei Universe Mobile</title><style>
html,body{margin:0;height:100%;background:#02050d;color:#eaf2ff;font-family:ui-monospace,monospace;overflow:hidden}#c{width:100%;height:100%;display:block;touch-action:none}.top{position:fixed;left:10px;right:10px;top:10px;background:#07101ddd;border:1px solid #234767;border-radius:14px;padding:10px 12px;backdrop-filter:blur(8px);z-index:4}.top b{letter-spacing:.14em}.meta{font-size:11px;opacity:.8;margin-top:4px}.sheet{position:fixed;left:10px;right:10px;bottom:10px;max-height:34vh;overflow:auto;background:#07101eee;border:1px solid #234767;border-radius:14px;padding:12px;z-index:5}.hidden{display:none}.ok{color:#70ffb1}.warn{color:#ffd66d}.bad{color:#ff6f86}.tiny{font-size:11px;opacity:.82}.tag{display:inline-block;margin-top:6px;padding:3px 7px;border:1px solid #31597b;border-radius:999px;font-size:10px;opacity:.85}</style></head><body>
<canvas id="c"></canvas><div class="top"><b>KOSCHEI UNIVERSE</b><div id="meta" class="meta">loading observer state…</div></div><div id="sheet" class="sheet hidden"></div>
<script>
const c=document.getElementById('c'),x=c.getContext('2d'),meta=document.getElementById('meta'),sheet=document.getElementById('sheet');let U=null,pts=[],scale=1,ox=0,oy=0,last=null,down=null;
function fit(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);layout()}addEventListener('resize',fit);fit();
function status(n){let ks=new Set((n.events||[]).map(e=>e.kind));if(n.quarantined||ks.has('fork')||ks.has('rollback')||ks.has('quarantine'))return'bad';if(ks.has('admission-denied')||ks.has('budget-block')||ks.has('authority-death'))return'warn';return'ok'}
function layout(){if(!U)return;let cx=innerWidth/2,cy=innerHeight*.54,unit=Math.min(innerWidth,innerHeight)/1500;pts=(U.nodes||[]).map(n=>{let sp=n.spatial||{},a=(sp.angleMicrorad||0)/1e6,r=(sp.radiusUnits||0)*unit,s=Math.max(14,(sp.sizeUnits||34)*unit);return{n,x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r,r:s}})}
function T(p){return{x:(p.x+ox-innerWidth/2)*scale+innerWidth/2,y:(p.y+oy-innerHeight/2)*scale+innerHeight/2,r:p.r*scale}}
function stars(){for(let i=0;i<110;i++){let px=(i*89+17)%innerWidth,py=(i*47+31)%innerHeight;x.fillStyle=i%9===0?'#9dc7ff30':'#ffffff18';x.fillRect(px,py,i%13===0?1.5:1,i%13===0?1.5:1)}}
function draw(){requestAnimationFrame(draw);x.clearRect(0,0,innerWidth,innerHeight);stars();if(!U)return;let by=Object.fromEntries(pts.map(p=>[p.n.id,p]));for(let e of (U.edges||[])){let a=by[e.source],b=by[e.destination];if(!a||!b)continue;let A=T(a),B=T(b),active=e.relation==='conduit';x.strokeStyle=active?'#5ad9ff88':'#6f82aa55';x.lineWidth=active?2:1;x.beginPath();x.moveTo(A.x,A.y);x.lineTo(B.x,B.y);x.stroke()}for(let p of pts){let q=T(p),s=status(p.n),col=s==='bad'?'#ff5d78':s==='warn'?'#ffd05d':p.n.kind==='project'?'#a878ff':'#5de6ff';x.shadowColor=col;x.shadowBlur=p.n.kind==='project'?26:16;x.fillStyle=col+'44';x.beginPath();x.arc(q.x,q.y,q.r,0,Math.PI*2);x.fill();x.shadowBlur=0;x.strokeStyle=col;x.lineWidth=p.n.kind==='project'?2:1;x.stroke();x.fillStyle='#edf6ff';x.font=Math.max(9,10.5*scale)+'px ui-monospace';x.textAlign='center';let label=(p.n.id||'').replace(/^project:|^module:/,'');x.fillText(label,q.x,q.y+q.r+14)}}
function pick(px,py){return pts.find(p=>{let q=T(p);return Math.hypot(px-q.x,py-q.y)<=q.r+14})}
function show(n){let ev=(n.events||[]).map(e=>`<div class="tiny">${e.kind} · epoch ${e.epoch}</div>`).join('')||'<div class="tiny">no live events</div>';let sp=n.spatial||{};sheet.innerHTML=`<b>${n.id}</b><div class="${status(n)}">${n.kind} · ${status(n)}</div><div class="tag">ring ${sp.ring??'?'} · canonical spatial</div><div class="tag">authority-free observer</div>${ev}`;sheet.classList.remove('hidden')}
c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);last={id:e.pointerId,x:e.clientX,y:e.clientY};down={x:e.clientX,y:e.clientY}});c.addEventListener('pointermove',e=>{if(!last||last.id!==e.pointerId)return;ox+=(e.clientX-last.x)/scale;oy+=(e.clientY-last.y)/scale;last={id:e.pointerId,x:e.clientX,y:e.clientY}});c.addEventListener('pointerup',e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<8){let p=pick(e.clientX,e.clientY);if(p)show(p.n)}last=null;down=null});c.addEventListener('wheel',e=>{e.preventDefault();scale=Math.min(3,Math.max(.55,scale*(e.deltaY>0?.9:1.1)))},{passive:false});
async function load(){try{let r=await fetch('/api/observer',{cache:'no-store',credentials:'same-origin'});if(r.status===401){location.replace('/login');return}if(!r.ok)throw Error(r.status);let env=await r.json();let next=env.payload||env.universe||env;let changed=!U||U.projection!==next.projection||U.state!==next.state||U.layout!==next.layout;U=next;meta.innerHTML=`epoch <span class="ok">${U.epoch??'?'}</span> · nodes ${(U.nodes||[]).length} · layout ${(U.layout||'').slice(0,8)} · read-only`;if(changed)layout()}catch(e){meta.innerHTML='<span class="bad">observer state unavailable</span>'}}
load();setInterval(load,2000);draw();
</script></body></html>'''
