"""Koschei Universe Mobile View v1.

Touch-first read-only renderer for authority-free remote observer envelopes.
This module contains no mutation API and does not persist bearer credentials.
"""
from __future__ import annotations

MOBILE_HTML_V1 = r'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><title>Koschei Universe Mobile</title><style>
html,body{margin:0;height:100%;background:#02050d;color:#eaf2ff;font-family:ui-monospace,monospace;overflow:hidden}#c{width:100%;height:100%;display:block;touch-action:none}.top{position:fixed;left:10px;right:10px;top:10px;background:#07101ddd;border:1px solid #234767;border-radius:14px;padding:10px 12px;backdrop-filter:blur(8px);z-index:4}.top b{letter-spacing:.14em}.meta{font-size:11px;opacity:.8;margin-top:4px}.sheet{position:fixed;left:10px;right:10px;bottom:10px;max-height:34vh;overflow:auto;background:#07101eee;border:1px solid #234767;border-radius:14px;padding:12px;z-index:5}.hidden{display:none}.ok{color:#70ffb1}.warn{color:#ffd66d}.bad{color:#ff6f86}.tiny{font-size:11px;opacity:.82}</style></head><body>
<canvas id="c"></canvas><div class="top"><b>KOSCHEI UNIVERSE</b><div id="meta" class="meta">observer idle</div></div><div id="sheet" class="sheet hidden"></div>
<script>
const c=document.getElementById('c'),x=c.getContext('2d'),meta=document.getElementById('meta'),sheet=document.getElementById('sheet');let U=null,pts=[],scale=1,ox=0,oy=0,last=null,pinch=null;
function fit(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);layout()}addEventListener('resize',fit);fit();
function status(n){let ks=new Set((n.events||[]).map(e=>e.kind));if(n.quarantined||ks.has('fork')||ks.has('rollback')||ks.has('quarantine'))return'bad';if(ks.has('admission-denied')||ks.has('budget-block')||ks.has('authority-death'))return'warn';return'ok'}
function layout(){if(!U)return;let cx=innerWidth/2,cy=innerHeight/2,R=Math.min(innerWidth,innerHeight)*.28;pts=(U.nodes||[]).map((n,i)=>{let a=Math.PI*2*i/Math.max(U.nodes.length,1)-Math.PI/2;return{n,x:cx+Math.cos(a)*R,y:cy+Math.sin(a)*R,r:n.kind==='project'?30:19}})}
function T(p){return{x:(p.x+ox-innerWidth/2)*scale+innerWidth/2,y:(p.y+oy-innerHeight/2)*scale+innerHeight/2,r:p.r*scale}}
function draw(){requestAnimationFrame(draw);x.clearRect(0,0,innerWidth,innerHeight);for(let i=0;i<90;i++){x.fillStyle='#ffffff18';x.fillRect((i*89)%innerWidth,(i*47)%innerHeight,1,1)}if(!U)return;let by=Object.fromEntries(pts.map(p=>[p.n.id,p]));for(let e of (U.edges||[])){let a=by[e.source],b=by[e.destination];if(!a||!b)continue;let A=T(a),B=T(b);x.strokeStyle=e.relation==='conduit'?'#5ad9ff88':'#6f82aa55';x.lineWidth=e.relation==='conduit'?2:1;x.beginPath();x.moveTo(A.x,A.y);x.lineTo(B.x,B.y);x.stroke()}for(let p of pts){let q=T(p),s=status(p.n),col=s==='bad'?'#ff5d78':s==='warn'?'#ffd05d':'#5de6ff';x.shadowColor=col;x.shadowBlur=16;x.fillStyle=col+'44';x.beginPath();x.arc(q.x,q.y,q.r,0,Math.PI*2);x.fill();x.shadowBlur=0;x.strokeStyle=col;x.stroke();x.fillStyle='#edf6ff';x.font=Math.max(10,11*scale)+'px ui-monospace';x.textAlign='center';x.fillText(p.n.id,q.x,q.y+q.r+15)}}
function pick(px,py){return pts.find(p=>{let q=T(p);return Math.hypot(px-q.x,py-q.y)<=q.r+12})}
function show(n){let ev=(n.events||[]).map(e=>`<div class="tiny">${e.kind} · epoch ${e.epoch}</div>`).join('')||'<div class="tiny">no live events</div>';sheet.innerHTML=`<b>${n.id}</b><div class="${status(n)}">${n.kind} · ${status(n)}</div>${ev}`;sheet.classList.remove('hidden')}
c.addEventListener('pointerdown',e=>{c.setPointerCapture(e.pointerId);last={id:e.pointerId,x:e.clientX,y:e.clientY};});c.addEventListener('pointermove',e=>{if(!last||last.id!==e.pointerId)return;ox+=(e.clientX-last.x)/scale;oy+=(e.clientY-last.y)/scale;last={id:e.pointerId,x:e.clientX,y:e.clientY}});c.addEventListener('pointerup',e=>{if(last&&Math.hypot(e.clientX-last.x,e.clientY-last.y)<5){let p=pick(e.clientX,e.clientY);if(p)show(p.n)}last=null});c.addEventListener('wheel',e=>{e.preventDefault();scale=Math.min(2.8,Math.max(.6,scale*(e.deltaY>0?.9:1.1)))},{passive:false});
async function load(){let url=new URL(location.href),token=url.hash.startsWith('#token=')?decodeURIComponent(url.hash.slice(7)):'';if(token)history.replaceState(null,'',location.pathname+location.search);if(!token){meta.textContent='observer token required';return}try{let r=await fetch('/api/observer',{headers:{Authorization:'Bearer '+token},cache:'no-store'});if(!r.ok)throw Error(r.status);let env=await r.json();U=env.payload||env.universe||env;meta.innerHTML=`epoch <span class="ok">${U.epoch??'?'}</span> · nodes ${(U.nodes||[]).length} · read-only`;layout()}catch(e){meta.innerHTML='<span class="bad">observer state unavailable</span>'}}load();draw();
</script></body></html>'''
